import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Sale, ShopSettings } from '../types';
import { money } from './money';
import { fmtDateTime } from './dates';

export function generateInvoicePdf(sale: Sale, shop: ShopSettings, forClient = true) {
  const doc = new jsPDF();
  const accent: [number, number, number] = [201, 162, 39];

  if (shop.logoDataUrl) {
    try {
      doc.addImage(shop.logoDataUrl, 'PNG', 14, 12, 22, 22);
    } catch {
      /* ignore invalid logo */
    }
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(...accent);
  doc.text(shop.name, shop.logoDataUrl ? 42 : 14, 22);

  doc.setTextColor(30);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(shop.ownerName, shop.logoDataUrl ? 42 : 14, 28);
  doc.text(shop.address, shop.logoDataUrl ? 42 : 14, 33);
  doc.text(`${shop.phone} · ${shop.email}`, shop.logoDataUrl ? 42 : 14, 38);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(forClient ? 'CLIENT INVOICE' : 'SHOP COPY', 140, 22);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Invoice: ${sale.invoiceNumber}`, 140, 30);
  doc.text(`Date: ${fmtDateTime(sale.createdAt)}`, 140, 36);
  doc.text(`Payment: ${sale.paymentMethod.toUpperCase()}`, 140, 42);
  doc.text(`Staff: ${sale.staffName}`, 140, 48);

  doc.setFont('helvetica', 'bold');
  doc.text('Bill to', 14, 55);
  doc.setFont('helvetica', 'normal');
  doc.text(sale.customerName + (sale.isGuest ? ' (Guest)' : ''), 14, 61);

  autoTable(doc, {
    startY: 70,
    head: [['Product', 'Qty', 'Unit', 'Total']],
    body: sale.items.map((i) => [
      i.productName,
      String(i.quantity),
      money(i.unitPrice, shop.currency),
      money(i.lineTotal, shop.currency),
    ]),
    theme: 'striped',
    headStyles: { fillColor: accent, textColor: 20 },
  });

  const finalY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
  const lines = [
    [`Subtotal (ex TVA)`, money(sale.subtotalExTva + sale.discountAmount, shop.currency)],
    sale.discountAmount > 0
      ? [`Discount`, `-${money(sale.discountAmount, shop.currency)}`]
      : null,
    [`Subtotal after discount`, money(sale.subtotalExTva, shop.currency)],
    [`TVA (${sale.tvaPercent}%)`, money(sale.tvaAmount, shop.currency)],
    [`Total (inc TVA)`, money(sale.totalIncTva, shop.currency)],
  ].filter(Boolean) as [string, string][];

  lines.forEach(([label, value], idx) => {
    const y = finalY + idx * 7;
    doc.setFont('helvetica', idx === lines.length - 1 ? 'bold' : 'normal');
    doc.text(label, 120, y);
    doc.text(value, 196, y, { align: 'right' });
  });

  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text('Thank you for visiting. Generated by RBT Manager.', 14, 285);

  return doc;
}

export function downloadInvoice(sale: Sale, shop: ShopSettings, forClient = true) {
  const doc = generateInvoicePdf(sale, shop, forClient);
  doc.save(`${sale.invoiceNumber}-${forClient ? 'client' : 'shop'}.pdf`);
}

export function openInvoicePreview(sale: Sale, shop: ShopSettings, forClient = true) {
  const doc = generateInvoicePdf(sale, shop, forClient);
  window.open(doc.output('bloburl'), '_blank');
}

export function mailtoInvoice(sale: Sale, shop: ShopSettings, email?: string) {
  const subject = encodeURIComponent(`Invoice ${sale.invoiceNumber} — ${shop.name}`);
  const body = encodeURIComponent(
    `Hello ${sale.customerName},\n\nPlease find your invoice ${sale.invoiceNumber} for ${money(sale.totalIncTva, shop.currency)}.\nPayment: ${sale.paymentMethod}.\n\nOpen RBT Manager to download/print the PDF invoice.\n\n${shop.name}`,
  );
  const to = email || '';
  window.location.href = `mailto:${to}?subject=${subject}&body=${body}`;
}
